// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4gAiN3OijRbq1jMzaQSm1U20hG1u-_s',
    appId: '1:450619226215:web:be4047559a3caaec6afcc2',
    messagingSenderId: '450619226215',
    projectId: 'sampah-cf336',
    authDomain: 'sampah-cf336.firebaseapp.com',
    storageBucket: 'sampah-cf336.firebasestorage.app',
    measurementId: 'G-ENQRXHGBC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJhc-KDilGyNEPPh97Y_u884fZkxxsilk',
    appId: '1:450619226215:android:06bbb6c95839adac6afcc2',
    messagingSenderId: '450619226215',
    projectId: 'sampah-cf336',
    storageBucket: 'sampah-cf336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk-fyGvWbn3m6WeKhEwkGuJ14pE6djmOg',
    appId: '1:450619226215:ios:bd8e7fd8eac7d0e46afcc2',
    messagingSenderId: '450619226215',
    projectId: 'sampah-cf336',
    storageBucket: 'sampah-cf336.firebasestorage.app',
    iosBundleId: 'com.example.papb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk-fyGvWbn3m6WeKhEwkGuJ14pE6djmOg',
    appId: '1:450619226215:ios:bd8e7fd8eac7d0e46afcc2',
    messagingSenderId: '450619226215',
    projectId: 'sampah-cf336',
    storageBucket: 'sampah-cf336.firebasestorage.app',
    iosBundleId: 'com.example.papb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW4gAiN3OijRbq1jMzaQSm1U20hG1u-_s',
    appId: '1:450619226215:web:4604d4c1e8d56f646afcc2',
    messagingSenderId: '450619226215',
    projectId: 'sampah-cf336',
    authDomain: 'sampah-cf336.firebaseapp.com',
    storageBucket: 'sampah-cf336.firebasestorage.app',
    measurementId: 'G-7JNM3C0MMX',
  );
}
